---
role:
  pkg:
    - name: xo/xo/usql
      os: ["darwin"]
  link:
    - ".usqlrc"
  post_install:
    - "if test ! -f ~/.usqlpass; then echo '# protocol:host:port:dbname:user:pass' > ~/.usqlpass; chmod 0600 ~/.usqlpass; fi"
