---
role:
  pkg:
    - name: xo/xo/usql
      os: ["darwin"]
  link:
    - ".usqlrc"
  post_install:
    - "test ! -f ~/.usqlpass && (echo '# protocol:host:port:dbname:user:pass' > ~/.usqlpass) && chmod 0600 ~/.usqlpass"
